Repository intel/he-toolkit, pull requests merged in 2021-09, with the labels that each got.

#43 Revert Palisade to last stable release (1.11.3) with HEXL
  docker/setup_and_run_docker.sh
  docker/utils/gitops.sh
Labels: bug

#45 Initial HElib integration
  .github/workflows/github-ci.yml
  docker/Dockerfile.base
  docker/Dockerfile.toolkit
  docker/setup_and_run_docker.sh
  he-samples/CMakeLists.txt
  he-samples/cmake/helib.cmake
Labels: enhancement

#52 Expands description and adds sample kernel description tables
  he-samples/sample-kernels/README.md
Labels: documentation
